services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    volumes:
      - issue_manager_data:/pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  issue_manager_data:
